# Project: ¸´Ï°
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "review\ main.o" review.o
LINKOBJ  = "review main.o" review.o
LIBS     = -L"D:/Download/AppGallery/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Download/AppGallery/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Download/AppGallery/Dev-Cpp/TDM-GCC-64/include" -I"D:/Download/AppGallery/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Download/AppGallery/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Download/AppGallery/Dev-Cpp/TDM-GCC-64/include" -I"D:/Download/AppGallery/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Download/AppGallery/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Download/AppGallery/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = ¸´Ï°.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Download\AppGallery\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"review\ main.o": review\ main.c
	$(CC) -c "review main.c" -o "review main.o" $(CFLAGS)

review.o: review.c
	$(CC) -c review.c -o review.o $(CFLAGS)
